---
title: "Generalized Linear Models (GLMs)"
subtitle: "BMLR Chapter 5"
format: 
  revealjs:
    output-file: "05_glm_ch5.html"
    slide-number: true
  html:
    output-file: "05_glm_ch5_o.html"
logo: "/img/favicon.png"
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(tidymodels)
library(GGally)
library(knitr)
library(patchwork)
library(viridis)
library(ggfortify)
library(gridExtra)
```



## Learning goals 

- Explain the use of generalized linear models

- Identify the components common to all generalized linear models 

- Find the canonical link based on the distribution of the response variable 




# General Linear Models (GLMs)

## Why are GLMs useful? {.smaller}

- Linear regression models are used to predict $\mu_{y|x}$.
  - We assume that $Y$ has a normal distribution with mean $\mu_{y|x}$ and variance $\sigma^2$.
  - The model we use is $\mu_{y|x}=\beta_0 + \beta_1~x_1 + \beta_2~x_2 +...$
  - Note the unknown parameter is on the left and a linear combination of the predictor variables is on the right.
- What if the response variable $Y$ doesn't have a normal distribution?  Can we estimate a relevant parameter of its actual distribution?  
- If a GLM exists, then it gives us a way of estimating the relevant parameter using a linear combination of the predictor variables.

## Many models; one family {.smaller}

We will see three different situations where glms are appropriate:

- linear regression (response has a Normal distribution)
- logistic regression (response has a Bernoulli or Binomial distribution)
- poisson regression (response has a Poisson or Negative Binomial distribution)

. . .

All of these cases lead to models that are examples of **generalized linear models**.

GLMs have a similar structure for their likelihoods, MLEs, and variances, so we can use a generalized approach to find the model estimates and associated uncertainty.


## Components of a GLM {.smaller}

[Nelder and Wdderburn (1972)](https://sakai.duke.edu/access/content/group/ec265469-bdb3-47a7-beb0-317956b6f86f/GLM-paper.pdf) define a broad class of models called **generalized linear models** that generalizes multiple linear regression. GLMs are characterized by three components: 

. . .

`r emo::ji("one")` The response variable has a probability function with parameter $\theta$ that can be written in exponential family form (**random component**)

. . .

`r emo::ji("two")` There exists a linear combination of predictors, $\eta = \beta_1 x_1 + \beta_2 x_2 + \dots + \beta_p x_p$ (**systematic component**) so that:

. . .

`r emo::ji("three")` A **link** function $g(\theta)$ exists that connects $\theta$ to $\eta$

::: aside
Nelder, J. A., & Wedderburn, R. W. (1972). Generalized linear models. Journal of the Royal Statistical Society: Series A (General), 135(3), 370-384.
:::

## Math identities that are needed

- $a=e^{\log(a)}$

- $a^x = e ^ {x\log(a)}$

- $\log(ab)= \log(a) + \log(b)$

- $\log\left(\frac{a}{b}\right) = \log(a)-\log(b)$


## Exponential family form {.smaller}

Suppose a probability (mass or density) function has a parameter $\theta$. It is said to have a **one-parameter exponential family form** if 

. . .

`r emo::ji("white_check_mark")`  The support (set of possible values) does not depend on $\theta$, and 

. . .

`r emo::ji("white_check_mark")` The probability function can be written in the following form

$f(y;\theta) = e^{[a(y)b(\theta) + c(\theta) + d(y)]}$

. . .

Using this form: 

$$E(Y) = -\frac{c'(\theta)}{b'(\theta)} \hspace{20mm} Var(Y) = \frac{b''(\theta)c'(\theta) - c''(\theta)b'(\theta)}{[b'(\theta)]^3}$$

. . .

Note these last two equations use calculus, so we will not use them.


## Poisson in exponential family form {.smaller}

What if our response variable has a Poisson distribution?  Can we write the distribution funciton in exponential family form?

$$P(Y = y) = \frac{e^{-\lambda}\lambda^y}{y!} \hspace{10mm} y = 0, 1, 2, \ldots, \infty$$

. . .

$$\begin{aligned}P(Y = y) &= e^{-\lambda}e^{y\log(\lambda)}e^{-\log(y!)}\\
& = e^{y\log(\lambda) - \lambda - \log(y!)}\end{aligned}$$

. . .

Recall the form: $f(y;\theta) = e^{[a(y)b(\theta) + c(\theta) + d(y)]}$, where the parameter $\theta = \lambda$ for the Poisson distribution

:::: {.columns}
::: {.column}
- $a(y) = y$
- $b(\lambda) = \log(\lambda)$

:::

:::{.column}

- $c(\lambda) = -\lambda$
- $d(y) = -\log(y!)$

:::
::::

## Poisson in exponential family form {.smaller}

- The support for the Poisson distribution is $y = 0, 1, 2, \ldots, \infty$. This does not depend on the parameter $\lambda$. 

- The probability mass function can be written in the form $f(y;\theta) = e^{[a(y)b(\theta) + c(\theta) + d(y)]}$

. . .

**The Poisson distribution can be written in one-parameter exponential family form.**



## Canonical link {.smaller}

Suppose there is a response variable $Y$ from a distribution with parameter $\theta$ and a set of predictors that can be written as a linear combination $\eta = \sum_{j=1}^{p}\beta_jx_j = \beta_1 x_1 + \beta_2 x_2 + \dots + \beta_p x_p$

<br>

**(There does not have to be an intercept but generally we also include $\beta_0$)**

<br> 

. . .

A **link function**, $g()$, is a monotonic and differentiable function that connects $\theta$ to $\eta$

. . .

The **canonical link** is a link function such that $g(\theta) = \eta$

- When working with a member of the one-parameter exponential family, the canonical link is $b(\theta)$



## Canonical link for Poisson {.smaller}

Recall 

$$P(Y = y) = e^{y\log(\lambda) - \lambda - \log(y!)}$$

then the canonical link is $b(\lambda) = \log(\lambda)$



## GLM framework: Poisson response variable {.smaller}

`r emo::ji("one")` Response variable with parameter $\theta$ whose probability function can be written in exponential family form

$$P(Y = y) = e^{y\log(\lambda) - \lambda - \log(y!)}$$

. . .

`r emo::ji("two")` A linear combination of predictors, $\eta = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \dots + \beta_p x_p$

. . .

`r emo::ji("three")` A function $g(\lambda)$ that connects $\lambda$ and $\eta$ 

$$\log(\lambda) = \eta =  \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \dots + \beta_p x_p$$
This means that our linear model will estimate $\log(\lambda)$ rather than just $\lambda$.


## Activity: Identifying canonical link {.smaller}

For the distribution 

- Describe an example of a setting where this random variable may be used.

- Identify the parameter.

- Write the pmf or pdf in one-parameter exponential form. 

- Identify the canonical link function

- One person from each group: Write your response on the board. 



## Activity {.smaller}

**Distributions**

1. Binary 
2. Exponential
3. Negative binomial (with fixed $r$)
4. Geometric
5. Normal (with fixed $\sigma$)

- If your group finishes early, try identifying the canonical link for the other distributions. 

- See [BMLR - Section 3.6](https://bookdown.org/roback/bookdown-BeyondMLR/ch-distthry.html#additional-resources) for details on the distributions.




## Acknowledgements {.smaller}

- These slides are based on content in [BMLR: Chapter 4](https://bookdown.org/roback/bookdown-BeyondMLR/)

- Initial versions of the slides are by Dr. Maria Tackett, Duke University

- [BMLR: Chapter 5 - Generalized Linear Models: A Unifying Theory](https://bookdown.org/roback/bookdown-BeyondMLR/ch-glms.html)
- Nelder, J. A., & Wedderburn, R. W. (1972). Generalized linear models. Journal of the Royal Statistical Society: Series A (General), 135(3), 370-384.
- Generalized Linear Models with Examples in R
  - Chapter 5 - Generalized Linear Models: Structure
  - Chapter 6 - Generalized Linear Models: Estimation 
  
