{
  "hash": "c166cd5393089d7e720eac6cbf635ede",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Welcome and Chapter 1\"\nauthor: \"Ann Cannon\"\nformat: \n  revealjs:\n    output-file: \"01-welcome_ch1.html\"\n    slide-number: true\n  html:\n    output-file: \"01-welcome_ch1_o.html\"\nlogo: \"../img/favicon.png\"\n---\n\n# Welcome!\n\n## Instructor\n\n- {{< var instructor.name >}}: [{{< var instructor.email >}}](mailto:acannon@cornellcollege.edu)\n\n\n\n## Course logistics\n\n- Course Dates: {{< var course.dates >}}\n- Course sessions: {{< var course.time >}}\n- Exam Dates: {{< var course.exam_dates >}}\n\n\n## What we're covering this block (1/3)\n\n**Generalized Linear Models (Ch 1 - 6)**\n\n- Introduce models for non-normal response variables\n- Estimation, interpretation, and inference\n- Mathematical details showing how GLMs are connected\n\n\n## Generalized Linear Models {.smaller}\n\n*In statistics, a generalized linear model (GLM) is a flexible generalization of ordinary linear regression. The GLM generalizes linear regression by allowing the linear model to be related to the response variable via a link function and by allowing the magnitude of the variance of each measurement to be a function of its predicted value.* \n\n::: aside\n\n[Wikipedia](https://en.wikipedia.org/wiki/Generalized_linear_model)\n\n:::\n\n. . .\n\n**Logistic regression**\n\n$$\\begin{aligned}\\pi = P(y = 1 | x) \\hspace{2mm} &\\Rightarrow \\hspace{2mm} \\text{Link function: } \\log\\big(\\frac{\\pi}{1-\\pi}\\big) \\\\\n&\\Rightarrow \\log\\big(\\frac{\\pi}{1-\\pi}\\big) = \\beta_0 + \\beta_1~x\\end{aligned}$$\n\n\n\n\n## What we're covering this block (2/3)\n\n**Modeling correlated data (Ch 7 - 9)**\n\n- Introduce multilevel models for correlated and longitudinal data\n- Estimation, interpretation, and inference\n- Mathematical details, particularly diving into covariance structures\n\n## What we're covering this block (3/3)\n\n**More Regression Models (ITSL Chapter 7)**\n- Polynomial Regression\n- Regression Splines\n- Smoothing Splines\n- Generalized Additive Models (GAMS)\n\n\n## What background is assumed for the course? {.smaller}\n\n. . .\n\n**Pre-reqs**\n\n- STA 201, 202 and DSC 223\n\n. . .\n\n**Background knowledge** \n\n:::: {.columns}\n\n::: {.column }\n- Statistical content\n  - Linear and logistic regression \n  - Statistical inference\n  - Basic understanding of random variables\n  \n:::\n\n::: {.column}\n- Computing \n  - Using R for data analysis\n  - Writing reports using R Markdown or Quarto\n  \n:::\n::::\n\n## Course Toolkit (1/2)\n\n\n- **Website**\n  - [{{< var course.url >}}]({{< var course.url >}})\n  - Central hub for the course\n  - Notes\n  - Labs\n\n\n## Course Toolkit (2/2){.smaller}\n\n- **Moodle**: \n  - [{{< var course.moodle >}}]({{< var course.moodle >}})\n  - Submissions\n  - Announcements\n  \n- **R Server**:\n  - [{{< var college.rstudio >}}]({{ var college.rstudio >}})\n  - Datasets\n  - Quarto file storage\n\n\n## Class Meetings \n\n- Lecture\n- Individual and group labs\n- Mini-projects\n- Exams\n- Bring a fully-charged laptop\n\n. . .\n\n**Attendance is expected (if you are healthy!)**\n\n\n## Textbook\n\n:::: {.columns}\n\n::: {.column }\n\n![](img/bmlr.jpeg)\n\n\n:::\n\n::: {.column}\n*Beyond Multiple Linear Regression* by Paul Roback and Julie Legler\n\n- Available [online](https://bookdown.org/roback/bookdown-BeyondMLR/)\n- Hard copies available for purchase\n\n:::\n::::\n\n## Textbook 2\n\n{{< var course.text2 >}}\n\n- Hard copies available for purchase\n\n\n## Using R / RStudio\n- RStudio Server is installed and should be used\n- [{{< var college.rstudio >}}]({{< var college.rstudio >}})\n\n\n## Activities & Assessments {.smaller}\n\n\n**Readings**\n\n- Primarily from *Beyond Multiple Linear Regression* \n- Recommend reading assigned text before lecture\n\n. . .\n\n**Homework**\n- Primarily from *Beyond Multiple Linear Regression* \n\n- Individual assignments\n\n- Work together but must complete your own work. Discuss but don't copy. \n\n\n## Activities & Assessments {.smaller}\n\n**Mini-projects**\n\n- Mini-project 01: Focused on logistic regression models\n- Mini-project 02: Focused on models for response variables that represent count data\n- Mini-project 03: Focused on data collected at multiple levels\n\n. . .\n\n- Short write up and short presentation\n- Team-based\n\n\n## Exams\n- Two exams this block, {{< var course.exam_dates >}}. \n\n- Each will have two components\n  - Component 1 will be on these dates and will be a closed-book, closed-note, in-class exam.\n  - Component 2 will be a take-home, open-book, open-note exam. \n  - You will have 12 hours or more to complete the second component. \n\n\n## Grading\n\nFinal grades will be calculated as follows\n\n\n| Category              | Points     |\n|-----------------------|------------|\n| Homework              | 300        |\n| Labs & Participation  | 75         |\n| Mini Projects         | 225        |\n| Exams                 | 400        |\n| Total                 | 1000       |\n\n\n\n\n\n\n## Resources {.smaller}\n\n- **Office hours** to meet with your instructor in {{< var instructor.office >}}\n  - Typically {{< var instructor.officehrs >}}\n\n- **Email** {{< var instructor.name_no_title >}} for private questions regarding personal matters or grades. \n\n- College support at [{{< var college.support >}}]({{< var college.support >}}).\n\n# Chapter 1 - Linear Regression Review\n\n## Setup - R Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(latex2exp)\nlibrary(GGally)\nlibrary(knitr)\nlibrary(patchwork)\nlibrary(viridis)\nlibrary(ggfortify)\nlibrary(tailor)\nderby <- read_csv(\"data/derbyplus.csv\")\n```\n:::\n\n\n## Simple linear regression {.smaller}\n\n\n[Simplest case]{.fragment fragment-index=0}\n\n\n[$X=$ explanatory variable]{.fragment fragment-index=1 style=\"padding-left: 20px;\"}\n\n[$Y=$ response variable]{.fragment fragment-index=2 style=\"padding-left: 20px;\"}\n\n[Both variables are quantitative]{.fragment fragment-index=3 style=\"padding-left: 20px;\"}\n\n\n<br>\n\n\n[Model]{.fragment fragment-index=4}\n\n\n[$Y_i = \\beta_0 + \\beta_1 x_i + \\epsilon_i$ where $\\epsilon_i \\sim N\\left( 0,\\sigma^2\\right)$]{.fragment fragment-index=5 style=\"padding-left: 20px;\"}\n  \n\n::: {#slide-right-box .absolute .fragment top=\"70%\" left=\"45%\" width=\"30%\" height=\"20%\" style=\"background-color: #e6f2ff; border: 2px solid #0066cc; border-radius: 8px; padding: 20px; font-size: 0.75em;\" fragment-index=6}\n### Note \nThe book uses $\\sigma^2$ in this notation, not $\\sigma$ as we did in STA 201 and STA 202\n\n:::\n\n\n\n## Assumptions for linear regression {.smaller}\n\nWhat are the assumptions for linear regression? \n. . .\n\n**L**inearity: Linear relationship between mean response and predictor variable(s) \n\n. . .\n\n**I**ndependence: Residuals are independent. There is no connection between how far any two points lie above or below regression line.\n\n. . .\n\n**N**ormality: Response follows a normal distribution at each level of the predictor (or combination of predictors)\n\n. . .\n\n**E**qual variance: Variability (variance or standard deviation) of the response is equal for all levels of the predictor (or combination of predictors)\n\n. . .\n\n**Use residual plots to check that the conditions hold before using the model for statistical inference.**\n\n\n\n## Assumptions for linear regression {.smaller}\n\n:::: {.columns}\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](01-welcome_ch1_files/figure-revealjs/unnamed-chunk-2-1.png){width=100%}\n:::\n:::\n\n\n\n\n::: aside\nModified from Figure 1.1. in BMLR]\n:::\n\n:::\n\n::: {.column width = \"60%\"}\n\n- **L**inearity: Linear relationship between mean of the response $Y$ and the predictor $X$\n\n- **I**ndependence: No connection between how any two points lie above or below the regression line\n\n- **N**ormality: Response, $Y$, follows a normal distribution at each level of the predictor, $X$ (indicated by red curves)\n\n- **E**qual variance: Variance (or standard deviation) of the response, $Y$, is equal for all levels of the predictor, $X$\n\n:::\n::::\n\n\n## Example\n\nSea ice data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsi <- read_csv(\"data/seaice.csv\")\nhead(si)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n   year    mo source_dataset region extent  area\n  <dbl> <dbl> <chr>          <chr>   <dbl> <dbl>\n1  1979     9 NSIDC-0051     N        7.05  4.58\n2  1980     9 NSIDC-0051     N        7.67  4.87\n3  1981     9 NSIDC-0051     N        7.14  4.44\n4  1982     9 NSIDC-0051     N        7.3   4.43\n5  1983     9 NSIDC-0051     N        7.39  4.7 \n6  1984     9 NSIDC-0051     N        6.81  4.11\n```\n\n\n:::\n:::\n\n\n## Sea ice data information {.smaller}\n\nThe National Oceanic and Atmospheric Administration measures the amount of sea ice in both the arctic and antarctic on a regular basis (at least daily). \n\nOur data:\n\n - Average amount of ice for the month of September in the Arctic\n \n - September is the month with the least amount of ice in the Arctic\n \n - Data from 1979 - 2025 (September isn't over yet so we don't have 2026 yet)\n - Area = the total region covered by ice\n \n - Extent = the total region with at least 15% ice cover (think about a slice of swiss cheese)\n\n\n\n\n## Is the relationship linear? \n\n::: {.panel-tabset}\n\n### Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01-welcome_ch1_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = si, aes(x = year, y = extent)) + \n  geom_point() + \n  geom_smooth(method = \"lm\", se = FALSE) + \n  labs(x = \"Year\", y = \"Extent of Ice\", \n       title = \"Year vs. Extent of Ice\") \n```\n:::\n\n\n:::\n\n## Compute the model \n\n\n::: {.panel-tabset}\n\n### Output\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |  158.155|    11.277|    14.025|       0|\n|year        |   -0.076|     0.006|   -13.504|       0|\n\n\n:::\n:::\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit and display model\nmodel1 <- lm(extent ~ year, data=si)\ntidy(model1) |> kable(digits = 3)\n```\n:::\n\n\n:::\n\n## Interpretation {.smaller}\n\n$$\\widehat{extent} = 158.155 - 0.076 ~ year$$\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |  158.155|    11.277|    14.025|       0|\n|year        |   -0.076|     0.006|   -13.504|       0|\n\n\n:::\n:::\n\n\n. . .\n\n\n1. Write out the interpretations for `year`. \n2. Does the intercept have a meaningful interpretation? \n\n\n## Center the data\n\n::: {.panel-tabset}\n\n### Create new variable\n\n - We only have data starting in 1979.  So let's call that year 0.  The data at the beginning of the study.\n\n - Create a new variable: $time = year - 1979$\n \n - This is called centering\n \n\n::: {.cell}\n\n:::\n\n \n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit and display model\nsi |>\n  mutate(c_year = year-1979) -> si\n```\n:::\n\n\n:::\n\n## Interpret new model {.smaller}\n\n$$\\widehat{extent} = 7.625 - 0.076 ~ year$$\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |    7.625|     0.150|    50.693|       0|\n|c_year      |   -0.076|     0.006|   -13.504|       0|\n\n\n:::\n:::\n\n\n. . .\n\n\nQuestions:\n\n - 1. What is the interpretation of the y-intercept now? \n \n - 2. Did the slope change?\n\n\n \n\n## Check assumptions {.smaller}\n\n::: {.panel-tabset}\n\n### Output\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01-welcome_ch1_files/figure-revealjs/unnamed-chunk-11-1.png){width=960}\n:::\n:::\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the diagnostic plots\npar(mfrow=c(2,2))\n\nplot(model2, pch=16, col='#006EA1')\n```\n:::\n\n\n`pch` defines the shape of the plotted symbol\n\n`col` defines the color of the plotted symbol\n:::\n\n## What about the curvature?\n\nTry polynomial regression:\n\n$$y_i = \\beta_0 + \\beta_1 ~ xi + \\beta_2 ~x_i^2 + \\beta_3 ~ x_i^3 ... + \\beta_d ~ x_i^d + \\epsilon_i $$\n \n . . .\n\nIn this case, maybe a cubic (why?):\n\n$$\\widehat{extent} = \\hat{\\beta}_0 + \\hat{\\beta}_1 ~ c\\_year + \\hat{\\beta}_2 ~c\\_year^2 + \\hat{\\beta}_3 ~ c\\_year^3 $$\n\n## New model {.smaller}\n\n::: {.panel-tabset}\n\n### Output\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term             | estimate| std.error| statistic| p.value|\n|:----------------|--------:|---------:|---------:|-------:|\n|(Intercept)      |    5.875|     0.069|    85.003|   0.000|\n|poly(c_year, 3)1 |   -7.074|     0.474|   -14.928|   0.000|\n|poly(c_year, 3)2 |   -0.040|     0.474|    -0.084|   0.933|\n|poly(c_year, 3)3 |    1.640|     0.474|     3.462|   0.001|\n\n\n:::\n:::\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit and display model\nmodel3 <- lm(extent ~ poly(c_year,3), data=si)\ntidy(model3) |> kable(digits = 3)\n```\n:::\n\n\n:::\n\n## Check assumptions {.smaller}\n\n::: {.panel-tabset}\n\n### Output\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01-welcome_ch1_files/figure-revealjs/unnamed-chunk-14-1.png){width=960}\n:::\n:::\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the diagnostic plots\npar(mfrow=c(2,2))\n\nplot(model3, pch=16, col='#006EA1')\n```\n:::\n\n\n\n:::\n\n\n\n\n## Review of multiple linear regression \n\n\n\n## Data: Saratoga house prices {.smaller}\n\n\nData from homes for sale in Saratoga, NY.  The data is about 15 years old.\n\n. . .\n\n::::{.columns}\n:::{.column}\n\n**Response variable**\n\n- `Price`: Price of the home in 1000s of dollars\n\n:::\n\n:::{.column}\n\n**Predictor/Explanatory variables**\n\n- `Size`: Size of the home in 1000s of square feet\n- `Baths`: Number of bathrooms\n- `Bedrooms`: Number of bedrooms\n- `Fireplace`: Does it have a fireplace? 0 = No, 1 = Yes\n- `Acres`: Size of the lot in acres\n- `Age`:  Age of the home\n\n:::\n\n\n::::\n\n\n## Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsaratoga <- read_csv(\"data/saratoga.csv\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsaratoga |>\n  head(5) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|   Price|  Size| Baths| Bedrooms| Fireplace| Acres| Age|\n|-------:|-----:|-----:|--------:|---------:|-----:|---:|\n| 142.212| 1.982|   1.0|        3|         0|  2.00| 133|\n| 134.865| 1.676|   1.5|        3|         1|  0.38|  14|\n| 118.007| 1.694|   2.0|        3|         1|  0.96|  15|\n| 138.297| 1.800|   1.0|        2|         1|  0.48|  49|\n| 129.470| 2.088|   1.0|        3|         1|  1.84|  29|\n\n\n:::\n:::\n\n\n## Data Analysis Life Cycle\n\n![](img/data-analysis-life-cycle.png)\n\n\n\n## Exploratory data analysis (EDA) {.smaller}\n\n- Once you're ready for the statistical analysis (explore), the first step should always be **exploratory data analysis**.\n\n- The EDA will help you \n  - begin to understand the variables and observations\n  - identify outliers or potential data entry errors\n  - begin to see relationships between variables\n  - identify the appropriate model and identify a strategy\n\n- The EDA is exploratory; formal modeling and statistical inference should be used to draw conclusions.\n\n\n\n## Plots for univariate EDA\n\n\n::: {.panel-tabset}\n\n### Plot \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01-welcome_ch1_files/figure-revealjs/univar-eda-plot-1.png){width=960}\n:::\n:::\n\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(data = saratoga, aes(x = Price)) + \n  geom_histogram(fill = \"forestgreen\", color = \"black\") + \n  labs(x = \"Price ($1000)\", y = \"Count\")\n\np2 <- ggplot(data = saratoga, aes(x = Size)) + \n  geom_histogram(fill = \"forestgreen\", color = \"black\") + \n  labs(x = \"Size (1000 sqft)\", y = \"Count\")\n\np3 <- ggplot(data = saratoga, aes(x = Baths)) +\n   geom_bar(fill = \"forestgreen\", color = \"black\", aes(x = ))\n\np1 + (p2 / p3) + \n  plot_annotation(title = \"Univariate data analysis\")\n```\n:::\n\n\n:::\n\n\n## Plots for univariate EDA (cont.)\n\n\n::: {.panel-tabset}\n\n### Plot \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01-welcome_ch1_files/figure-revealjs/univar-eda-plot3-1.png){width=960}\n:::\n:::\n\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(data = saratoga, aes(x = Bedrooms)) + \n  geom_bar(fill = \"forestgreen\", color = \"black\", aes(x=))\n\np2 <- ggplot(data = saratoga, aes(x = Acres)) + \n  geom_histogram(fill = \"forestgreen\", color = \"black\") + \n  labs(x = \"Size of lot (acres)\", y = \"Count\")\n\np3 <- ggplot(data = saratoga, aes(x = Fireplace)) +\n   geom_bar(fill = \"forestgreen\", color = \"black\", aes(x = ))\n\np4 <- ggplot(data = saratoga, aes(x = Age)) + \n  geom_histogram(fill = \"forestgreen\", color = \"black\") + \n  labs(x = \"Age (years\", y = \"Count\")\n\n(p1 + p2) / (p3 + p4)  + \n  plot_annotation(title = \"Univariate data analysis\")\n```\n:::\n\n\n:::\n\n\n\n\n## Plots for bivariate EDA {.smaller}\n\n::: {.panel-tabset}\n\n### Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01-welcome_ch1_files/figure-revealjs/bivar-eda-plot-1.png){width=960}\n:::\n:::\n\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np5 <- ggplot(data = saratoga, aes(x = Size, y = Price)) + \n  geom_point() + \n  labs(x = \"Size (1000 sq ft)\", y = \"Price ($1000)\")\n\np6 <- ggplot(data = saratoga, aes(x = Age, y = Price)) + \n  geom_point() + \n  labs(x = \"Age (years)\", y = \"Price ($1000\")\n\np7 <- ggplot(data = saratoga, aes(x = as.factor(Fireplace), y = Price)) + \n  geom_boxplot(fill = \"forestgreen\", color = \"black\") + \n  labs(x = \"Fireplace (0 = no, 1 = yes)\", y = \"Price ($1000\")\n\n(p5 + p6) / p7 +\n  plot_annotation(title = \"Bivariate data analysis\")\n```\n:::\n\n\n:::\n\n## Scatterplot matrix {.smaller}\n\n\nA **scatterplot matrix** helps quickly visualize relationships between many variable pairs. They are particularly useful to identify potentially correlated predictors.\n\n. . .\n\n::: {.panel-tabset}\n\n### Plot\n\n::: {.cell}\n::: {.cell-output-display}\n![](01-welcome_ch1_files/figure-revealjs/scatterplot-matrix-plot-1.png){width=960}\n:::\n:::\n\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#library(GGally)\nggpairs(data = saratoga)\n```\n:::\n\n\n:::\n\n\n## Plots for multivariate EDA {.smaller}\n\nPlot the relationship between the response and a predictor based on levels of another predictor to assess potential interactions. \n\n::: {.panel-tabset}\n\n### Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01-welcome_ch1_files/figure-revealjs/multivar-eda-plot-1.png){width=960}\n:::\n:::\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#library(viridis)\nsaratoga$fire <- as.factor(saratoga$Fireplace)\nggplot(data = saratoga, aes(x = Size, y = Price, color = fire, \n                         shape = fire, linetype = fire)) + \n  geom_point() + \n  geom_smooth(method = \"lm\", se = FALSE, aes(linetype = fire)) + \n  labs(x = \"Size (1000 sq ft)\", y = \"Price ($1000)\", color = \"Fireplace\",\n       title = \"Price vs. size\", \n       subtitle = \"by whether it has a fireplace or not\") +\n  guides(lty = FALSE, shape = FALSE) +\n  scale_color_viridis_d(alpha = 0.6, end = 0.8) \n```\n:::\n\n\n:::\n\n\n\n## Model 1: Main effects model {.smaller}\n\n::: {.panel-tabset}\n\n### Output\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |    0.950|     7.562|     0.126|   0.900|\n|Size        |   80.073|     4.170|    19.204|   0.000|\n|Baths       |   25.279|     3.870|     6.532|   0.000|\n|Bedrooms    |   -9.014|     2.852|    -3.160|   0.002|\n|Acres       |    1.887|     2.080|     0.907|   0.364|\n|Fireplace   |    4.844|     3.776|     1.283|   0.200|\n|Age         |   -0.064|     0.051|    -1.244|   0.214|\n\n\n:::\n:::\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit and display model\npr.model1 <- lm(Price ~ Size + Baths + Bedrooms + Size + Acres + Fireplace + Age, data = saratoga)\ntidy(pr.model1) |> kable(digits = 3)\n```\n:::\n\n\n:::\n\n## [Interpretation]{style=\"font-size: 75%;\"} {.smaller}\n\n$$\n\\begin{aligned}\n\\widehat{Price} = & 0.950 + 80.073 ~ Size + 25.279 ~ Baths - 9.014 ~ Bedrooms + 1.887 ~ Acres \\\\\n& + 4.844 ~ Fireplace - 0.064 ~ Age\n \\end{aligned}\n$$\n\n::::{.columns}\n\n:::{.column}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate|\n|:-----------|--------:|\n|(Intercept) |    0.950|\n|Size        |   80.073|\n|Baths       |   25.279|\n|Bedrooms    |   -9.014|\n|Acres       |    1.887|\n|Fireplace   |    4.844|\n|Age         |   -0.064|\n\n\n:::\n:::\n\n\n:::\n\n:::{.column}\n\n1. Write out the interpretations for `Size` and `Fireplace`. \n2. Does the intercept have a meaningful interpretation? \n\n:::\n\n::::\n\n\n\n## Model 1: Check model assumptions {.smaller}\n\n::: {.panel-tabset}\n\n### Plots\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01-welcome_ch1_files/figure-revealjs/unnamed-chunk-22-1.png){width=960}\n:::\n:::\n\n\n### Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#library(ggfortify)\npar(mfrow=c(2,2))\n\nplot(pr.model1, pch=16, col='#006EA1')\n```\n:::\n\n\n\n\n### Questions\n\nWhich of the model assumptions (LINE) does this pass and/or fail? \n\n\n:::\n\n## Model 2: Add interaction term for Fireplace and Size? {.smaller}\n\n::: {.panel-tabset}\n\n### Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01-welcome_ch1_files/figure-revealjs/multivar-eda-plot2-1.png){width=960}\n:::\n:::\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#library(viridis)\n#saratoga$fire <- as.factor(saratoga$Fireplace)\nggplot(data = saratoga, aes(x = Size, y = Price, color = fire, \n                         shape = fire, linetype = fire)) + \n  geom_point() + \n  geom_smooth(method = \"lm\", se = FALSE, aes(linetype = fire)) + \n  labs(x = \"Size (1000 sq ft)\", y = \"Price ($1000)\", color = \"Fireplace\",\n       title = \"Price vs. size\", \n       subtitle = \"by whether it has a fireplace or not\") +\n  guides(lty = FALSE, shape = FALSE) +\n  scale_color_viridis_d(alpha = 0.6, end = 0.8) \n```\n:::\n\n\n:::\n\n\n\n## Model 2: Add $Fireplace * Size$ {.smaller}\n\n::: {.panel-tabset}\n\n### Output\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term           | estimate| std.error| statistic| p.value|\n|:--------------|--------:|---------:|---------:|-------:|\n|(Intercept)    |  45.0000|   10.0209|    4.4906|  0.0000|\n|Size           |  48.3306|    6.3482|    7.6132|  0.0000|\n|Baths          |  25.7862|    3.7966|    6.7919|  0.0000|\n|Bedrooms       |  -8.9452|    2.7976|   -3.1974|  0.0014|\n|Acres          |   2.0120|    2.0400|    0.9863|  0.3242|\n|Fireplace      | -59.3043|   10.4881|   -5.6544|  0.0000|\n|Age            |  -0.0518|    0.0503|   -1.0314|  0.3026|\n|Size:Fireplace |  40.5109|    6.1967|    6.5375|  0.0000|\n\n\n:::\n:::\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\npr.model2 <- lm(Price ~ Size + Baths + Bedrooms + Acres + Fireplace + Age +Fireplace*Size, data = saratoga)\ntidy(pr.model2) |> kable(digits = 4)\n```\n:::\n\n\n:::\n\n\n## Interpreting interaction effects with 0/1 variable\n\n$$\n\\begin{aligned}\n\\hat{y}& = \\hat{\\beta}_0 + \\hat{\\beta}_1 ~ x_1  + \\hat{\\beta}_2 ~ x_2 + \\hat{\\beta}_3 ~x_3 +\\hat{\\beta}_4 ~ x_1~x_2\\\\\n & = \\hat{\\beta}_0 + \\hat{\\beta}_1 ~ x_1 + \\hat{\\beta}_3 ~x_3\\hspace{3.9 in} \\text{  when } x_2=0\\\\\n & = (\\hat{\\beta}_0 +\\hat{\\beta}_2) + (\\hat{\\beta}_1 + \\hat{\\beta}_4) ~ x_1 +\\hat{\\beta}_3~x_3\\hspace{.75 in} \\text{  when } x_2=1\n\\end{aligned}\n$$\n\n\n**General interpretation**: When $x_2$ is present, the slope between $x_1$ and $y$ increases(decreases) by $\\hat{\\beta}_4$ units and the $y$-intercept increases(decreases) by $\\hat{\\beta}_2$ units when all other variables are held constant.\n\n\n\n\n\n## Interpreting quadratic effects {.smaller}\n\n$$\\begin{aligned}\\widehat{Price} = &45.00 + 48.33 ~ Size + 25.79 ~ Baths - 8.95 ~ Bedrooms \\\\\n& + 2.01 ~ Acres - 59.30 ~ Fireplace - 0.05 ~ Age + 40.51~Fireplace * Size\\end{aligned}$$\n\n. . .\n\nQuestion: \n\n*Interpret the effect that having a fireplace has on the relationship between size and price.*\n\n\n\n## Model 2: Check model assumptions\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01-welcome_ch1_files/figure-revealjs/unnamed-chunk-27-1.png){width=960}\n:::\n:::\n\n\n\n## Model 3: Try ln of response and delete some variables {.smaller}\n\n\n::: {.panel-tabset}\n\n### Output\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term           | estimate| std.error| statistic| p.value|\n|:--------------|--------:|---------:|---------:|-------:|\n|(Intercept)    |    4.092|     0.055|    74.866|   0.000|\n|Size           |    0.306|     0.035|     8.694|   0.000|\n|Baths          |    0.177|     0.020|     8.906|   0.000|\n|Bedrooms       |   -0.013|     0.015|    -0.850|   0.396|\n|Fireplace      |    0.081|     0.059|     1.390|   0.165|\n|Size:Fireplace |    0.026|     0.035|     0.743|   0.458|\n\n\n:::\n:::\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\npr.model3 <- lm(log(Price) ~ Size + Baths + Bedrooms  + Fireplace  + Fireplace*Size, data = saratoga)\ntidy(pr.model3) |> kable(digits = 3)\n```\n:::\n\n\n:::\n\n## Model 4: Fewer terms yet {.smaller}\n\n\n::: {.panel-tabset}\n\n### Output\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |    4.026|     0.028|   143.310|       0|\n|Size        |    0.344|     0.019|    17.817|       0|\n|Baths       |    0.195|     0.020|     9.790|       0|\n\n\n:::\n:::\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\npr.model4 <- lm(log(Price) ~ Size + Baths, data = saratoga)\ntidy(pr.model4) |> kable(digits = 3)\n```\n:::\n\n\n\n\n### Assumptions\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01-welcome_ch1_files/figure-revealjs/unnamed-chunk-32-1.png){width=960}\n:::\n:::\n\n\n\n:::\n\n## Which model would you choose?\n\n::: {.panel-tabset}\n\n\n### Model 1: Main effects\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| r.squared| adj.r.squared|     AIC|      BIC|\n|---------:|-------------:|-------:|--------:|\n|     0.621|         0.619| 11432.1| 11471.85|\n\n\n:::\n:::\n\n\n### Model 2: Main effects + interaction\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| r.squared| adj.r.squared|      AIC|     BIC|\n|---------:|-------------:|--------:|-------:|\n|     0.636|         0.633| 11391.88| 11436.6|\n\n\n:::\n:::\n\n\n### Model 4: Small model\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| r.squared| adj.r.squared|     AIC|     BIC|\n|---------:|-------------:|-------:|-------:|\n|     0.587|         0.586| 389.812| 409.687|\n\n\n:::\n:::\n\n\n### Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 1\nglance(pr.model1) |>\n  select(r.squared, adj.r.squared, AIC, BIC) |>\n  kable(digits = 3)\n\n# Model2\nglance(pr.model2) |>\n  select(r.squared, adj.r.squared, AIC, BIC) |>\n  kable(digits = 3)\n\n# Model 4\nglance(pr.model4) |>\n  select(r.squared, adj.r.squared, AIC, BIC) |>\n  kable(digits = 3)\n```\n:::\n\n\n:::\n\n## What are these model quality metrics? \n\n- **How do we define RSquared?**\n\n- **What is adj.r.squared?**\n\n\n## Measures of model performance {.smaller}\n\n- $\\color{#4187aa}{R^2}$: Proportion of variability in the response explained by the model.\n  -  Will always increase as predictors are added, so it shouldn't be used to compare models\n  \n- $\\color{#4187aa}{Adj. R^2}$: Similar to $R^2$ with a penalty for extra terms\n\n. . .\n\n- $\\color{#4187aa}{AIC}$: Likelihood-based approach balancing model performance and complexity\n\n- $\\color{#4187aa}{BIC}$: Similar to AIC with stronger penalty for extra terms\n\n. . . \n\n- **Nested F Test (extra sum of squares F test)**: Generalization of t-test for individual coefficients to perform significance tests on nested models\n\n\n## Which model would you choose? {.smaller}\n\nUse the **`glance`** function to get model statistics.\n\n::: {.panel-tabset}\n\n### Output\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|model  | r.squared| adj.r.squared|       AIC|       BIC|\n|:------|---------:|-------------:|---------:|---------:|\n|Model1 |     0.621|         0.619| 11432.097| 11471.847|\n|Model2 |     0.636|         0.633| 11391.883| 11436.603|\n|Model4 |     0.587|         0.586|   389.812|   409.687|\n\n\n:::\n:::\n\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1_glance <- glance(pr.model1) |>\n  select(r.squared, adj.r.squared, AIC, BIC)\nmodel2_glance <- glance(pr.model2) |>\n  select(r.squared, adj.r.squared, AIC, BIC)\nmodel4_glance <- glance(pr.model4) |>\n  select(r.squared, adj.r.squared, AIC, BIC)\n\nmodel1_glance |>\n  bind_rows(model2_glance) |>\n  bind_rows(model4_glance) |>\n  bind_cols(model = c(\"Model1\", \"Model2\", \"Model4\")) |>\n  select(model, everything()) |>\nkable(digits = 3)\n```\n:::\n\n\n:::\n\n## Characteristics of a \"good\" final model {.smaller}\n\n- Model can be used to answer primary research questions\n- Predictor variables control for important covariates\n- Potential interactions have been investigated\n- Variables are centered, as needed, for more meaningful interpretations \n- Unnecessary terms are removed \n- Assumptions are met and influential points have been addressed\n- Model tells a \"persuasive story parsimoniously\"\n\n::: aside\n[List from Section 1.6.7 of BMLR](https://bookdown.org/roback/bookdown-BeyondMLR/)\n:::\n\n\n## Inference for multiple linear regression {.smaller}\n\nUse statistical inference to \n\n- Determine if predictors are statistically significant (not necessarily practically significant!)\n- Quantify uncertainty in coefficient estimates\n- Quantify uncertainty in model predictions\n\n. . .\n\nIf L.I.N.E. assumptions are met, we can conduct inference using the $t$ distribution and estimated standard errors \n\n## Inference for regression {.smaller}\n\n::: {.panel-tabset}\n\n### When L.I.N.E. conditions are met \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01-welcome_ch1_files/figure-revealjs/unnamed-chunk-39-1.png){width=100%}\n:::\n:::\n\n\n### We can\n\n- Use least squares regression to get the estimates $\\hat{\\beta}_0$, $\\hat{\\beta}_1$, and $\\hat{\\sigma}^2$\n\n- $\\hat{\\sigma}$ is the **regression standard error** \n\n\n- $\\hat{\\sigma} = \\sqrt{\\frac{\\sum_{i=1}^n(y_i - \\hat{y}_i)^2}{n - p - 1}} = \\sqrt{\\frac{\\sum_{i=1}^n e_i^2}{n-p-1}}$\n\n:::\n\n\n## Beyond linear regression {.smaller}\n\n- When we use linear least squares regression to draw conclusions, we do so under the assumption that L.I.N.E. are all met. \n\n- **Generalized linear models** require different assumptions and can accommodate violations in L.I.N.E.\n  - Relationship between response and predictor(s) can be nonlinear\n  - Response variable can be non-normal \n  - Variance in response can differ at each level of predictor(s) \n\n. . .\n\n**But the independence assumption must hold!**\n\n- **Multilevel models** will be used for data with correlated observations\n\n\n\n## Acknowledgements\n\n- These slides are based on content in [BMLR: Chapter 1 - Review of Multiple Linear Regression](https://bookdown.org/roback/bookdown-BeyondMLR/ch-MLRreview.html)\n\n- Initial versions of the slides are by Dr. Maria Tackett, Duke University\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}