{
  "hash": "c38253a810941f6f010cd56429f349c2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logistic Regression\"\nsubtitle: \"BMLR Chapter 6\"\nformat: \n  revealjs:\n    output-file: \"06_logistic_ch6.html\"\n    slide-number: true\n  html:\n    output-file: \"06_logistic_ch6_o.html\"\nlogo: \"../img/favicon.png\"\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(GGally)\nlibrary(knitr)\nlibrary(patchwork)\nlibrary(viridis)\nlibrary(ggfortify)\nlibrary(gridExtra)\n```\n:::\n\n\n\n## Learning goals {.smaller}\n\n- Identify Bernoulli and binomial random variables\n\n- Write GLM for binomial response variable \n\n- Interpret the coefficients for a logistic regression model \n\n- Visualizations for logistic regression\n\n\n\n\n\n# Basics of logistic regression\n## Bernoulli + Binomial random variables (1/2) {.smaller}\n\nLogistic regression is used to analyze data with two types of responses: \n\n- **Binary**: These responses take on two values: success $(Y = 1)$ or failure $(Y = 0)$, yes $(Y = 1)$ or no $(Y = 0)$, etc.\n\n. . .\n\n$$P(Y = y) = p^y(1-p)^{1-y} \\hspace{10mm} y = 0, 1$$\n\n## Bernoulli + Binomial random variables (2/2)  {.smaller}\n\nLogistic regression is used to analyze data with two types of responses: \n\n- **Binomial**: Number of successes in a Bernoulli process, $n$ independent trials with a constant probability of success $p$. \n\n. . .\n\n$$P(Y = y) = {n \\choose y}p^{y}(1-p)^{n - y} \\hspace{10mm} y = 0, 1, \\ldots, n$$\n\n. . .\n\nIn both instances, the goal is to model $p$ the probability of success.\n\n\n\n## Binary vs. Binomial data {.smaller}\n\nFor each example, identify if the response is a Bernoulli or Binomial response\n\n\n1. Use median age and unemployment rate in a county to predict the percent of Obama votes in the county in the 2008 presidential election.\n\n2. Use GPA and MCAT scores to estimate the probability a student is accepted into medical school.\n\n3. Use sex, age, and smoking history to estimate the probability an individual has lung cancer.\n\n4. Use offensive and defensive statistics from the 2017-2018 NBA season to predict a team's winning percentage.\n\n## Logit link {.smaller}\n\nBernoulli and Binomial random variables can be written in one-parameter exponential family form, $f(y;\\theta) = e^{[a(y)b(\\theta) + c(\\theta) + d(y)]}$\n\n. . .\n\n**Bernoulli**\n\n$$f(y;p) = e^{y\\log(\\frac{p}{1-p}) + \\log(1-p)}$$\n\n. . .\n\n**Binomial** \n\n$$f(y;n,p) = e^{y\\log(\\frac{p}{1-p}) + n\\log(1-p) + \\log{n \\choose y}}$$\n\n. . .\n\nThey have the same canonical link $b(p) = \\log\\big(\\frac{p}{1-p}\\big)$\n\n\n\n\n## Logistic regression model {.smaller}\n\nSo the glm model for both cases is: \n\n$\\log\\Big(\\frac{p}{1-p}\\Big) = \\beta_0 + \\beta_1x_1 + \\beta_2x_2 + \\dots + \\beta_px_p$\n\n- The response variable, $\\log\\Big(\\frac{p}{1-p}\\Big)$, is the log(odds) of success, i.e. the logit\n\n\n- Use the model to calculate the probability of success $\\hat{p} = \\frac{e^{\\beta_0 + \\beta_1x_1 + \\beta_2x_2 + \\dots + \\beta_px_p}}{1 + e^{\\beta_0 + \\beta_1x_1 + \\beta_2x_2 + \\dots + \\beta_px_p}}$\n\n\n- When the response is a Bernoulli random variable, the probabilities can be used to classify each observation as a success or failure\n\n\n\n## Logistic vs linear regression model {.smaller}\n\n:::{.panel-tabset}\n\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Graph from BMLR Chapter 6](06_logistic_ch6_files/figure-html/OLSlogistic-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n### Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(0)\ndat <- tibble(x=runif(200, -5, 10),\n                  p=exp(-2+1*x)/(1+exp(-2+1*x)),\n                  y=rbinom(200, 1, p),\n                  y2=.3408+.0901*x,\n                  logit=log(p/(1-p)))\ndat2 <- tibble(x = c(dat$x, dat$x),\n               y = c(dat$y2, dat$p),\n               `Regression model` = c(rep(\"linear\", 200),\n                                      rep(\"logistic\", 200)))\n\nggplot() + \n  geom_point(data = dat, aes(x, y)) +\n  geom_line(data = dat2, aes(x, y, linetype = `Regression model`, \n                             color = `Regression model`)) + \n  labs(title = \"Linear vs. logistic regression models for binary response data\") + \n  scale_colour_manual(name = 'Regression model',\n                      values = c('blue', 'red'), \n                      labels = c('linear', 'logistic'), guide ='legend')\n```\n:::\n\n\n:::\n\n\n\n## Assumptions for logistic regression {.smaller}\n\nThe following assumptions need to be satisfied to use logistic regression to make inferences\n\n. . .\n\n1️⃣ $\\hspace{0.5mm}$ **Binary response**: The response is dichotomous (has two possible outcomes) or is the sum of dichotomous responses\n\n2️⃣ $\\hspace{0.5mm}$ **Independence**: The observations must be independent of one another \n\n3️⃣ $\\hspace{0.5mm}$ **Variance structure**: Variance of a binomial random variable is $np(1-p)$ $(n = 1 \\text{ for Bernoulli})$ , so the variability  is highest when $p = 0.5$\n\n4️⃣ $\\hspace{0.5mm}$  **Linearity**: The log of the odds ratio, $\\log\\big(\\frac{p}{1-p}\\big)$, must be a linear function of the predictors $x_1, \\ldots, x_p$\n\n\n\n## COVID-19 infection prevention practices at food establishments {.smaller}\n\nResearchers at Wollo Univeristy in Ethiopia conducted a study in July and August 2020 to understand factors associated with good COVID-19 infection prevention practices at food establishments. Their study is published in [Andualem et al. (2022)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0259851#ack) \n\n<br> \n\nThey were particularly interested in understanding the implementation of prevention practices at food establishments, given the workers' increased risk due to daily contact with customers. \n\n:::aside\nAndualem, A., Tegegne, B., Ademe, S., Natnael, T., Berihun, G., Abebe, M., ... & Adane, M. (2022). COVID-19 infection prevention practices among a sample of food handlers of food and drink establishments in Ethiopia. PloS one, 17(1), e0259851.\n:::\n\n\n## The data {.smaller}\n\n*\"An institution-based cross-sectional study was conducted among <b>422 food handlers in Dessie City and Kombolcha Town food and drink establishments in July and August 2020.</b> The study participants were selected using a <b>simple random sampling</b> technique. Data were collected by trained data collectors using a pretested structured questionnaire and an on-the-spot observational checklist.\"*\n\n\n:::aside\nAndualem, A., Tegegne, B., Ademe, S., Natnael, T., Berihun, G., Abebe, M., ... & Adane, M. (2022). COVID-19 infection prevention practices among a sample of food handlers of food and drink establishments in Ethiopia. PloS one, 17(1), e0259851.\n:::\n\n\n## Response variable {.smaller}\n\n*\"The outcome variable of this study was the <b>good or poor practices of COVID-19 infection prevention among food handlers</b>. Nine yes/no questions, one observational checklist and five multiple choice infection prevention practices questions were asked with a minimum score of 1 and maximum score of 25. Good infection prevention practice (the variable of interest) was determined for food handlers who scored 75% or above, whereas poor infection prevention practices refers to those food handlers who scored below 75% on the practice questions.\"* \n\n\n:::aside\nAndualem, A., Tegegne, B., Ademe, S., Natnael, T., Berihun, G., Abebe, M., ... & Adane, M. (2022). COVID-19 infection prevention practices among a sample of food handlers of food and drink establishments in Ethiopia. PloS one, 17(1), e0259851.\n:::\n\n\n\n## Results\n\n![](img/logistic-output.PNG){width=90%}\n\n:::aside\nAndualem, A., Tegegne, B., Ademe, S., Natnael, T., Berihun, G., Abebe, M., ... & Adane, M. (2022). COVID-19 infection prevention practices among a sample of food handlers of food and drink establishments in Ethiopia. PloS one, 17(1), e0259851.\n:::\n\n\n\n## Interpreting the results {.smaller}\n\n- Is the response a Bernoulli or Binomial? \n\n- What is the strongest predictor of having good COVID-19 infection prevention practices?\n  \n  \n- Describe the effect (coefficient interpretation and inference) of having COVID-19 infection prevention policies available at the food establishment. \n\n- The intercept describes what group of food handlers? \n\n\n# Visualizations for logistic regression\n\n## Access to personal protective equipment {.smaller}\n\nWe will use the data from [Andualem et al. (2022)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0259851#ack) to explore the association between age, sex, years of service, and whether someone works at a food establishment with access to personal protective equipment (PPE) as of August 2020. We will use access to PPE as a proxy for wearing PPE. \n\n::: {.panel-tabset}\n\n### Data \n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 401 Columns: 58\n── Column specification ──────────────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (58): Age of food handlers, Sex, Years of service, Specific budget for PPE, Availa...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\n| age|sex    | years| ppe_access|\n|---:|:------|-----:|----------:|\n|  34|Male   |     2|          1|\n|  32|Female |     3|          1|\n|  32|Female |     1|          1|\n|  40|Male   |     4|          1|\n|  32|Male   |    10|          1|\n\n\n:::\n:::\n\n\n### Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_df <- read_csv(\"data/covid-prevention-study.csv\") |>\n  rename(age = \"Age of food handlers\", \n         years = \"Years of service\", \n         ppe_access = \"Availability of PPEs\") |>\n  mutate(sex = factor(if_else(Sex == 2, \"Female\", \"Male\"))) |>\n  select(age, sex, years, ppe_access) \n\ncovid_df |> slice(1:5) |> kable()\n```\n:::\n\n\n:::\n\n## EDA for binary response (1/2)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(Stat2Data)\npar(mfrow = c(1, 2))\nemplogitplot1(ppe_access ~ age, data = covid_df, ngroups = 10)\nemplogitplot1(ppe_access ~ years, data = covid_df, ngroups = 5)\n```\n\n::: {.cell-output-display}\n![](06_logistic_ch6_files/figure-html/unnamed-chunk-4-1.png){width=60%}\n:::\n:::\n\n\n\n\n## EDA for binary response (2/2) {.smaller}\n\n:::{.panel-tabset}\n\n### plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_logistic_ch6_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(viridis)\nggplot(data = covid_df, aes(x = sex, fill = factor(ppe_access))) + \n  geom_bar(position = \"fill\")  +\n  labs(x = \"Sex\", \n       fill = \"PPE Access\", \n       title = \"PPE Access by Sex\") + \n  scale_fill_viridis_d()\n```\n:::\n\n\n:::\n\n\n## Model results {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nppe_model <- glm(factor(ppe_access) ~ age + sex + years, data = covid_df, \n                 family = binomial)\ntidy(ppe_model, conf.int = TRUE) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept) |   -2.127|     0.458|    -4.641|   0.000|   -3.058|    -1.257|\n|age         |    0.056|     0.017|     3.210|   0.001|    0.023|     0.091|\n|sexMale     |    0.341|     0.224|     1.524|   0.128|   -0.098|     0.780|\n|years       |    0.264|     0.066|     4.010|   0.000|    0.143|     0.401|\n\n\n:::\n:::\n\n\n\n\n## Visualizing coefficient estimates {.smaller}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_coef <- tidy(ppe_model, exponentiate = TRUE, conf.int = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = model_coef, aes(x = term, y = estimate)) +\n  geom_point() +\n  geom_hline(yintercept = 1, lty = 2) + \n  geom_pointrange(aes(ymin = conf.low, ymax = conf.high))+\n  labs(title = \"Exponentiated model coefficients\") + \n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](06_logistic_ch6_files/figure-html/unnamed-chunk-9-1.png){width=55%}\n:::\n:::\n\n\n\n# Logistic regression for binomial response variable\n\n## Data: Supporting railroads in the 1870s {.smaller}\n\nThe data set [`RR_Data_Hale.csv`](data/RR_Data_Hale.csv) contains information on support for referendums related to railroad subsidies for 11 communities in Alabama in the 1870s. The data were originally analyzed as part of a thesis project by a student at St. Olaf College. The variables in the data are \n\n- `pctBlack`: percentage of Black residents in the county \n- `distance`: distance the proposed railroad is from the community (in miles)\n- `YesVotes`: number of \"yes\" votes in favor of the proposed railroad line \n- `NumVotes`: number of votes cast in the election \n\n. . .\n\n**Primary question**: Was voting on the railroad referendum related to the distance from the proposed railroad line, after adjusting for the racial composition of a community?\n\n\n\n## The data {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrr <- read_csv(\"data/RR_Data_Hale.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 12 Columns: 8\n── Column specification ──────────────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): County\ndbl (7): popBlack, popWhite, popTotal, pctBlack, distance, YesVotes, NumVotes\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nrr |> slice(1:5) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|County          | popBlack| popWhite| popTotal| pctBlack| distance| YesVotes| NumVotes|\n|:---------------|--------:|--------:|--------:|--------:|--------:|--------:|--------:|\n|Carthage        |      841|      599|     1440|    58.40|       17|       61|      110|\n|Cederville      |     1774|      146|     1920|    92.40|        7|        0|       15|\n|Five Mile Creek |      140|      626|      766|    18.28|       15|        4|       42|\n|Greensboro      |     1425|      975|     2400|    59.38|        0|     1790|     1804|\n|Harrison        |      443|      355|      798|    55.51|        7|        0|       15|\n\n\n:::\n:::\n\n\n\n\n## EDA (1/3) {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrr <- rr |>\n  mutate(pctYes = YesVotes/NumVotes, \n         emp_logit = log(pctYes / (1 - pctYes)))\n\nrr |> head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 10\n  County   popBlack popWhite popTotal pctBlack distance YesVotes NumVotes pctYes emp_logit\n  <chr>       <dbl>    <dbl>    <dbl>    <dbl>    <dbl>    <dbl>    <dbl>  <dbl>     <dbl>\n1 Carthage      841      599     1440     58.4       17       61      110 0.555      0.219\n2 Cedervi…     1774      146     1920     92.4        7        0       15 0       -Inf    \n3 Five Mi…      140      626      766     18.3       15        4       42 0.0952    -2.25 \n4 Greensb…     1425      975     2400     59.4        0     1790     1804 0.992      4.85 \n5 Harrison      443      355      798     55.5        7        0       15 0       -Inf    \n```\n\n\n:::\n:::\n\n\n## EDA (2/3) {.smaller}\n\n:::{.panel-tabset}\n\n### Plot \n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing non-finite outside the scale range (`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 3 rows containing non-finite outside the scale range (`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 1 row containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](06_logistic_ch6_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n### Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(data = rr, aes(x = distance, y = emp_logit)) + \n  geom_point() + \n  geom_smooth(method  = \"lm\", se = FALSE) + \n  labs(x = \"Distance to proposed railroad\", \n       y = \" \")\n  \np2 <- ggplot(data = rr, aes(x = pctBlack, y = emp_logit)) + \n  geom_point() + \n  geom_smooth(method  = \"lm\", se = FALSE) + \n  labs(x = \"% Black residents\", \n       y = \"\")\np1 + p2 + plot_annotation(title = \"Log(odds yes vote) vs. predictor variables\")\n```\n:::\n\n\n:::\n\n## EDA (3/3) {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrr <- rr |>\n  mutate(inFavor = if_else(pctYes > 0.5, \"Yes\", \"No\"))\n```\n:::\n\n\n::: {.panel-tabset}\n\n### Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_logistic_ch6_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = rr, aes(x = distance, y = pctBlack, color = inFavor)) + \n  geom_point() + \n  geom_smooth(method  = \"lm\", se = FALSE, aes(lty = inFavor)) + \n  labs(x = \"Distance to proposed railroad\", \n       y = \"% Black residents\",\n       title = \"% Black residents vs. distance\", \n       subtitle = \"Based on vote outcome. Check for potential multicollinearity and interaction effect\") + \n  scale_color_viridis_d(end = 0.85)\n```\n:::\n\n\n:::\n\n\n## Model \n\nLet $p$ be the percent of yes votes in a county. We'll start by fitting the following model: \n\n$$\\log\\Big(\\frac{p}{1-p}\\Big)  = \\beta_0 + \\beta_1 ~ dist + \\beta_2 ~ pctBlack$$\n\n\n\n\n## Model in R {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrr_model <- glm(cbind(YesVotes, NumVotes - YesVotes) ~ distance + pctBlack, \n                data = rr, family = binomial)\ntidy(rr_model, conf.int = TRUE) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept) |    4.222|     0.297|    14.217|   0.000|    3.644|     4.809|\n|distance    |   -0.292|     0.013|   -22.270|   0.000|   -0.318|    -0.267|\n|pctBlack    |   -0.013|     0.004|    -3.394|   0.001|   -0.021|    -0.006|\n\n\n:::\n:::\n\n\n. . .\n\n$$\\log\\Big(\\frac{\\hat{p}}{1-\\hat{p}}\\Big)  = 4.22 - 0.292 ~ dist - 0.013 ~ pctBlack$$\n\n::: aside\nSee Section 6.5 of *Generalized Linear Models with Examples in R* by Dunn and Smyth (available through Duke library) for details on estimating the standard errors.\n:::\n\n\n## Residuals {.smaller}\n\nFor logistic regression, there are two types of residuals: Pearson and deviance residuals\n\n. . .\n\n**Pearson residuals** \n\nPearson residuals look at the differences between actual and predicted counts.\n\n$$\\text{Pearson residual}_i = \\frac{\\text{actual count} - \\text{predicted count}}{\\text{SD count}} = \\frac{Y_i - m_i\\hat{p}_i}{\\sqrt{m_i\\hat{p}_i(1 - \\hat{p}_i)}}$$\n\n## Deviance residuals {.smaller}\n\nThe deviance residuals also compare the actual and predicted counts, but do so using the theory of likelihoods.\n\n**Deviance residuals** \n\n$$d_i = \\text{sign}(Y_i - m_i\\hat{p}_i)\\sqrt{2\\left[Y_i\\log\\left(\\frac{Y_i}{m_i\\hat{p}_i}\\right) + (m_i - Y_i)\\log\\left(\\frac{m_i - Y_i}{m_i - m_i\\hat{p}_i}\\right)\\right]}$$\nwhere \n\n$$\\text{sign}(y_i - m_i\\hat{p}_i)  =  \\begin{cases}\n1 & \\text{ if }(y_i - m_i\\hat{p}_i) > 0 \\\\\n-1 & \\text{ if }(y_i - m_i\\hat{p}_i) < 0 \\\\\n0 & \\text{ if }(y_i - m_i\\hat{p}_i) = 0\n\\end{cases}$$\n\n$\\Sigma d_i =$ deviance or residual deviance\n\n## Meaning of Residuals {.smaller}\n\nBoth types of residuals indicate how much the observed data deviates from the fitted model. What happens when the actual count and the predicted count are the same for each type of residual?\n\n. . .\n\n$$\\text{Pearson residual}_i = \\frac{\\text{actual count} - \\text{predicted count}}{\\text{SD count}} = \\frac{Y_i - m_i\\hat{p}_i}{\\sqrt{m_i\\hat{p}_i(1 - \\hat{p}_i)}}$$\n\n. . .\n\n$$d_i = \\text{sign}(Y_i - m_i\\hat{p}_i)\\sqrt{2\\left[Y_i\\log\\left(\\frac{Y_i}{m_i\\hat{p}_i}\\right) + (m_i - Y_i)\\log\\left(\\frac{m_i - Y_i}{m_i - m_i\\hat{p}_i}\\right)\\right]}$$\n\n## Plot of deviance residuals {.smaller}\n\n:::{.panel-tabset}\n\n### Model {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrr_aug <- augment(rr_model, type.predict = \"response\", \n                        type.residuals = \"deviance\")\n\nrr_aug |> slice(1:5) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|.rownames | cbind(YesVotes, NumVotes - YesVotes)| distance| pctBlack| .fitted|    .resid|      .hat|    .sigma|  .cooksd|  .std.resid|\n|:---------|------------------------------------:|--------:|--------:|-------:|---------:|---------:|---------:|--------:|-----------:|\n|1         |                                   61|       49|       17|   58.40| 0.1809492|  8.771817| 0.4024062| 5.049182|  38.9100153|\n|2         |                                    0|       15|        7|   92.40| 0.7226596| -6.202846| 0.0475431| 6.173926|   0.6827913|\n|3         |                                    4|       38|       15|   18.28| 0.4023246| -4.470391| 0.5021377| 6.176880|  11.1227469|\n|4         |                                 1790|       14|        0|   59.38| 0.9688288|  6.822432| 0.8365269| 1.792364| 341.6089578|\n|5         |                                    0|       15|        7|   55.51| 0.8093268| -7.050945| 0.0191686| 6.053687|   0.4228691|\n\n\n:::\n:::\n\n\n\n### Residual Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_logistic_ch6_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n### Plot Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = rr_aug, aes(x = .fitted, y = .resid)) + \n  geom_point() + \n  geom_hline(yintercept = 0, color = \"red\") + \n  labs(x = \"Fitted values\", \n       y = \"Deviance residuals\", \n       title = \"Deviance residuals vs. fitted\")\n```\n:::\n\n\n:::\n\n## Fit an interaction term {.smaller}\n\n:::{.panel-tabset}\n\n### Model {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrr_int_model <- glm(cbind(YesVotes, NumVotes-YesVotes) ~ distance + pctBlack +\n                      distance*pctBlack, data=rr, family=binomial)\nrr_int_aug <- augment(rr_int_model, type.predict = \"response\", \n                        type.residuals = \"deviance\")\n\nrr_int_aug |> slice(1:5) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|.rownames | cbind(YesVotes, NumVotes - YesVotes)| distance| pctBlack| .fitted|    .resid|      .hat|    .sigma|   .cooksd|  .std.resid|\n|:---------|------------------------------------:|--------:|--------:|-------:|---------:|---------:|---------:|---------:|-----------:|\n|1         |                                   61|       49|       17|   58.40| 0.2075801|  7.964510| 0.4663943| 5.0884957|  32.9667672|\n|2         |                                    0|       15|        7|   92.40| 0.6776101| -5.827504| 0.0492925| 6.3049338|   0.4298496|\n|3         |                                    4|       38|       15|   18.28| 0.2024659| -1.885115| 0.6433983| 6.6366201|   3.7828247|\n|4         |                                 1790|       14|        0|   59.38| 0.9760416|  5.230746| 0.8996698| 0.5044966| 452.2582760|\n|5         |                                    0|       15|        7|   55.51| 0.8513123| -7.561561| 0.0240118| 5.9951340|   0.5412285|\n\n\n:::\n:::\n\n\n\n### Residual Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_logistic_ch6_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n### Plot Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = rr_int_aug, aes(x = .fitted, y = .resid)) + \n  geom_point() + \n  geom_hline(yintercept = 0, color = \"red\") + \n  labs(x = \"Fitted values\", \n       y = \"Deviance residuals\", \n       title = \"Deviance residuals vs. fitted\")\n```\n:::\n\n\n:::\n\n\n## Goodness of fit {.smaller}\n\nWe use the sum of the squared deviance residuals to assess goodness of fit of the model. \n\n$$\\begin{aligned} &H_0: \\text{ Model is a good fit} \\\\\n&H_a: \\text{ Model is not a good fit}\\end{aligned}$$\n\n\n- When $m_i$ is large and the model is a good fit $(H_0 \\text{ true})$ the residual deviance follows a $\\chi^2$ distribution with $n - p$ degrees of freedom. \n  - Recall $n - p$ is the residual degrees of freedom.\n\n- If the model fits, we expect the residual deviance to be approximately what value? \n\n## Goodness of fit test {.smaller}\n\n:::{.panel-tabset}\n\n### Model {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrr_int_model <- glm(cbind(YesVotes, NumVotes - YesVotes) ~ distance + pctBlack + distance*pctBlack, data = rr, family = binomial)\n\nrr_int_model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = cbind(YesVotes, NumVotes - YesVotes) ~ distance + \n    pctBlack + distance * pctBlack, family = binomial, data = rr)\n\nCoefficients:\n      (Intercept)           distance           pctBlack  distance:pctBlack  \n         7.550902          -0.614005          -0.064731           0.005367  \n\nDegrees of Freedom: 10 Total (i.e. Null);  7 Residual\n  (1 observation deleted due to missingness)\nNull Deviance:\t    988.4 \nResidual Deviance: 274.2 \tAIC: 320.5\n```\n\n\n:::\n:::\n\n\n\n### Test \n\nThe test statistic is the residual deviance: 274.2\n\nThe degrees of freedom are the residual df: 7\n\nWe find the p-value using the chi-square distribution r function\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1-pchisq(274.2, 7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nThe p-value is quite small, so there is significant evidence that the model is not a good fit.\n:::\n\n## Drop-in-deviance test {.smaller}\n\nIs our last model better than just a model with distance in it?  We can test that with a drop-in-deviance test.\n\n:::{.panel-tabset}\n\n### Test information\n\nThe hypotheses are:\n\n$$\\begin{aligned} &H_0: \\text{ Simpler model is enough} \\\\\n&H_a: \\text{ More complete model is better}\\end{aligned}$$\n\n- Note that one observation was omitted in the more complicated model because it was missing the race information.  To compare the models, we must use the same exact data set, so in running the simpler model, I eliminated that data point.\n\n### Simpler Model {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrr_simp_model <- glm(cbind(YesVotes, NumVotes - YesVotes) ~ distance, \n                data = rr[-11,], family = binomial)\n\ntidy(rr_simp_model) |> kable(digits=3)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |    3.309|     0.113|    29.252|       0|\n|distance    |   -0.288|     0.013|   -22.085|       0|\n\n\n:::\n:::\n\n\n\n### Test \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrop_in_dev <- anova(rr_simp_model, rr_int_model, test= \"Chisq\")\ndrop_in_dev\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: cbind(YesVotes, NumVotes - YesVotes) ~ distance\nModel 2: cbind(YesVotes, NumVotes - YesVotes) ~ distance + pctBlack + \n    distance * pctBlack\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1         9     318.44                          \n2         7     274.23  2   44.206 2.517e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nSo even though there are issues with the larger model, it is significantly better than the simpler one.\n\n:::\n\n# Overdispersion \n\n## Overdispersion  {.smaller}\n\n**Overdispersion**: There is more variability in the response than what is assumed by the Logistic model \n\n:::{.panel-tabset}\n\n### Estimated variance\n\n:::: {.columns}\n\n::: {.column}\n\n**Overall $\\hat{p}$**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nover_p_hat <- sum(rr$YesVotes)/sum(rr$NumVotes)\nover_p_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8815944\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column}\n\n**$\\hat{p}$ by Location summary stats**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrr |> mutate(p_hat = YesVotes/NumVotes) |>\n  summarise(mean = mean(p_hat), var = var(p_hat)) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|  mean|   var|\n|-----:|-----:|\n| 0.517| 0.148|\n\n\n:::\n:::\n\n\n:::\n\n::::\n\n### Binomial variance\n\nThe variance for the count in a binomial setting is $np(1-p)$.  Here we want the variance of $\\hat{p}$ instead of the count.  That variance is $\\frac{p(1-p)}{n}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar_p_hat <- over_p_hat*(1-over_p_hat)/12\nvar_p_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.008698811\n```\n\n\n:::\n:::\n\n\nNotice that our estimated variance of $\\hat{p}$ is 0.148, but our model assumes a variance of approximately 0.009.\n\n:::\n\n## Why overdispersion matters {.smaller}\n\nIf there is overdispersion, then there is more variation in the response than what's assumed by a Binomial model. This means \n\n❌  The standard errors of the model coefficients are artificially small \n\n❌  The p-values are artificially small \n\n❌  This could lead to models that are more complex than what is needed \n\n. . .\n\nWe can take overdispersion into account by\n\n  - inflating standard errors by multiplying them by a dispersion factor\n \n\n## Dispersion parameter  {.smaller}\n\nThe **dispersion parameter** is represented by $\\phi$\n\n\n$$\\hat{\\phi} =\\frac{\\text{deviance}}{\\text{residual df}} = \\frac{\\sum_{i=1}^{n}(\\text{Pearson residuals})^2}{n - p}$$\n\nwhere $p$ is the number of terms in the model (including the intercept)\n\n\n- If there is no overdispersion $\\hat{\\phi} = 1$\n\n- If there is overdispersion $\\hat{\\phi} >  1$\n\n\n\n\n## Adjusting for overdispersion (1/4) {.smaller} \n\n\n- We can adjust for overdispersion in the binomial regression model by using the dispersion parameter $$\\hat{\\phi} = \\sum \\frac{(\\text{Pearson residuals})^2}{n-p}$$\n  -  By multiplying by $\\hat{\\phi}$, we are accounting for the reduction in information we would expect from independent observations. \n\n\n\n## Adjusting for overdispersion (2/4) {.smaller}\n\n- We adjust for overdispersion using a **quasibinomial** model. \n  - \"Quasi\" reflects the fact we are no longer using a binomial model with true likelihood. \n  \n- The standard errors of the coefficients are $SE_{Q}(\\hat{\\beta}_j) = \\sqrt{\\hat{\\phi}} SE(\\hat{\\beta})$\n  - Inference is done using the $t$ distribution to account for extra variability \n\n## Adjusting for overdispersion (3/4) {.smaller}\n\n:::{.panel-tabset}\n\n### Quasibinomial output {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term              | estimate| std.error| statistic| p.value|\n|:-----------------|--------:|---------:|---------:|-------:|\n|(Intercept)       |    7.551|     4.585|     1.647|   0.144|\n|distance          |   -0.614|     0.412|    -1.490|   0.180|\n|pctBlack          |   -0.065|     0.066|    -0.982|   0.359|\n|distance:pctBlack |    0.005|     0.006|     0.832|   0.433|\n\n\n:::\n:::\n\n\n\n### Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\nrr_qua_model <- glm(cbind(YesVotes, NumVotes - YesVotes) ~ distance + pctBlack + distance*pctBlack, data = rr, family = quasibinomial)\n\ntidy(rr_qua_model) |> kable(digits=3)\n```\n:::\n\n:::\n\n## Adjusting for overdispersion (4/4) {.smaller}\n\n:::{.panel-tabset}\n\n### Without interaction output {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |    4.222|     1.990|     2.121|   0.067|\n|distance    |   -0.292|     0.088|    -3.323|   0.010|\n|pctBlack    |   -0.013|     0.026|    -0.506|   0.626|\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = cbind(YesVotes, NumVotes - YesVotes) ~ distance + \n    pctBlack, family = quasibinomial, data = rr)\n\nCoefficients:\n(Intercept)     distance     pctBlack  \n    4.22202     -0.29173     -0.01323  \n\nDegrees of Freedom: 10 Total (i.e. Null);  8 Residual\n  (1 observation deleted due to missingness)\nNull Deviance:\t    988.4 \nResidual Deviance: 307.2 \tAIC: NA\n```\n\n\n:::\n:::\n\n\n\n### Simple model output \n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |    3.340|     0.692|     4.824|   0.001|\n|distance    |   -0.289|     0.080|    -3.608|   0.005|\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = cbind(YesVotes, NumVotes - YesVotes) ~ distance, \n    family = quasibinomial, data = rr)\n\nCoefficients:\n(Intercept)     distance  \n     3.3399      -0.2893  \n\nDegrees of Freedom: 11 Total (i.e. Null);  10 Residual\nNull Deviance:\t    995.3 \nResidual Deviance: 321.2 \tAIC: NA\n```\n\n\n:::\n:::\n\n\n:::\n\n\n<!-- # Predicting emergency department wait and treatment times  -->\n\n\n\n<!-- ## Predicting ED wait and treatment times {.smaller} -->\n\n<!-- [Ataman and Sariyer (2021)](https://sakai.duke.edu/access/content/group/ec265469-bdb3-47a7-beb0-317956b6f86f/ataman-sariyer-2021.pdf) use ordinal logistic regression to predict patient wait and treatment times in an emergency department (ED).  The goal is to identify relevant factors that can be used to inform recommendations for reducing wait and treatment times, thus improving the quality of care in the ED.  -->\n\n<!-- **Data**: Daily records for ED arrivals in August 2018 at a public hospital in Izmir, Turkey.  -->\n\n<!-- **Response variable**: Wait time, a categorical variable with three levels:  -->\n<!--   - Patients who wait less than 10 minutes -->\n<!--   - Patients whose waiting time is in the range of 10-60 minutes -->\n<!--   - Patients who wait more than 60 minutes -->\n\n\n<!-- ::: aside -->\n<!-- Ataman, M. G., & Sarıyer, G. (2021). Predicting waiting and treatment times in emergency departments using ordinal logistic regression models. The American Journal of Emergency Medicine, 46, 45-50. -->\n<!-- ::: -->\n\n\n\n<!-- ## Ordinal logistic regression {.smaller} -->\n\n<!-- Let $Y$ be an ordinal response variable that takes levels $1, 2, \\ldots, J$ with associated probabilities $p_1, p_2, \\ldots, p_J$.  -->\n\n<!-- The **proportional odds model** can be written as the following: -->\n\n<!-- $$\\begin{aligned}&\\log\\Big(\\frac{P(Y\\leq 1)}{P(Y > 1)}\\Big) = \\beta_{01} + \\beta_1x_1 + \\dots +  \\beta_px_p \\\\ -->\n<!-- & \\log\\Big(\\frac{P(Y\\leq 2)}{P(Y > 2)}\\Big) = \\beta_{02} + \\beta_1x_1 + \\dots +  \\beta_px_p \\\\ -->\n<!-- & \\dots \\\\ -->\n<!-- & \\log\\Big(\\frac{P(Y\\leq J-1)}{P(Y > J-1)}\\Big) = \\beta_{0{J-1}} + \\beta_1x_1 + \\dots +  \\beta_px_p\\end{aligned}$$ -->\n\n<!-- ## Questions -->\n\n<!--   - How is the proportional odds model similar to the multinomial logistic model?  -->\n<!--   - How is it different? -->\n\n<!-- ## Effect of arrival mode {.smaller} -->\n\n<!-- ```{r echo = F, out.width = \"100%\"} -->\n\n<!-- knitr::include_graphics(\"img/oridinal-logistic-output.png\") -->\n<!-- ``` -->\n\n<!-- . . . -->\n\n<!-- **Question** -->\n\n<!-- The variable `arrival mode` takes two categories: ambulance and walk-in. Describe the effect of arrival mode in this model. Note that the baseline level is \"walk-in\". -->\n\n\n<!-- ## Effect of triage level {.smaller} -->\n\n<!-- . . . -->\n\n<!-- Consider the full output with the ordinal logistic models for wait and treatment times.  -->\n\n\n<!-- ```{r echo = F, out.width = \"90%\"} -->\n<!-- knitr::include_graphics(\"img/ordinal-model-full.png\") -->\n<!-- ``` -->\n\n\n<!-- - **Question** -->\n\n<!-- . . . -->\n\n<!-- Use the results from both models to describe the effect of triage level (red = urgent, green = non-urgent) on the wait and treatment times in the ED. Note that \"red\" is the baseline level. Is this what you expected?  -->\n\n  \n  \n\n## Acknowledgements\n\nThese slides are based on content in \n\n- [BMLR: Chapter 6 - Logistic Regression](https://bookdown.org/roback/bookdown-BeyondMLR/ch-logreg.html)\n\n- Initial versions of the slides are by Dr. Maria Tackett, Duke University\n- Originally edited by Tyler George\n\n  \n",
    "supporting": [
      "06_logistic_ch6_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}